export default {
  styleguideHome: 'styleguideHome',
  styleguideButton: 'StyleguideButton',
  styleguideInput: 'styleguideInput',
  styleguideTypography: 'styleguideTypography',
  styleguideToast: 'styleguideToast',
  login: 'login',
  SignIn: 'SignIn',
  Home: 'Home',
  MyAccount: 'MyAccount',
  BusinessDeal: 'BusinessDeal',
  Assets: 'Assets',
  PersonList: 'PersonList',
  PencilSearchPerson: 'PencilSearchPerson',
  ScanedPerson: 'ScanedPerson',
  TransferPaymentFinal: 'TransferPaymentFinal',
  EditMyAccountModal: 'EditMyAccountModal',
  BuyCoin: 'BuyCoin',
  TaskHome: 'TaskHome',
  Assets: 'Assets',
  VerifyPhone: 'VerifyPhone',
}
